# Generated by Django 4.2 on 2025-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_thumnail_shelf_thumbnail_shelf_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='name',
            field=models.CharField(default='Default Shelf', max_length=100),
        ),
    ]
